Dataset is currently located in the same folder as this file. Openining dataset using GitHub link does not work yet.

In [1]:
import pandas as pd
import numpy as np

# reads dataset and replaces linebreaks and missing values with ''
data = []
with open('chronic_kidney_disease_full.arff', "r") as f:
    for line in f:
        line = line.replace('\n', '')
        line = line.replace('?', '')
        data.append(line.split(','))

# gives names to the columns
names = ['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba',
         'bgr', 'bu',  'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc',
         'rbcc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane',
         'class', 'no_name']
    
df = pd.DataFrame(data[145:], columns=names)
# np.nan is recognised as missing value for Pandas functions e.g. isnull()
df = df.replace('', np.nan)

df

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class,no_name
0,48,80,1.020,1,0,NaN,normal,notpresent,notpresent,121,...,7800,5.2,yes,yes,no,good,no,no,ckd,NaN
1,7,50,1.020,4,0,NaN,normal,notpresent,notpresent,NaN,...,6000,NaN,no,no,no,good,no,no,ckd,NaN
2,62,80,1.010,2,3,normal,normal,notpresent,notpresent,423,...,7500,NaN,no,yes,no,poor,no,yes,ckd,NaN
3,48,70,1.005,4,0,normal,abnormal,present,notpresent,117,...,6700,3.9,yes,no,no,poor,yes,yes,ckd,NaN
4,51,80,1.010,2,0,normal,normal,notpresent,notpresent,106,...,7300,4.6,no,no,no,good,no,no,ckd,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,12,80,1.020,0,0,normal,normal,notpresent,notpresent,100,...,6600,5.4,no,no,no,good,no,no,notckd,NaN
398,17,60,1.025,0,0,normal,normal,notpresent,notpresent,114,...,7200,5.9,no,no,no,good,no,no,notckd,NaN
399,58,80,1.025,0,0,normal,normal,notpresent,notpresent,131,...,6800,6.1,no,no,no,good,no,no,notckd,NaN
400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# Drop unwanted columns
df.drop(columns=['rbc', 'pc','pcc','ba','sc','htn','dm','cad','appet','pe','ane', 'no_name'], inplace=True)
df

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc,class
0,48,80,1.020,1,0,121,36,NaN,NaN,15.4,44,7800,5.2,ckd
1,7,50,1.020,4,0,NaN,18,NaN,NaN,11.3,38,6000,NaN,ckd
2,62,80,1.010,2,3,423,53,NaN,NaN,9.6,31,7500,NaN,ckd
3,48,70,1.005,4,0,117,56,111,2.5,11.2,32,6700,3.9,ckd
4,51,80,1.010,2,0,106,26,NaN,NaN,11.6,35,7300,4.6,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,12,80,1.020,0,0,100,26,137,4.4,15.8,49,6600,5.4,notckd
398,17,60,1.025,0,0,114,50,135,4.9,14.2,51,7200,5.9,notckd
399,58,80,1.025,0,0,131,18,141,3.5,15.8,53,6800,6.1,notckd
400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# converts hemoglobin values from g/dl to d/l by multiplying by 10
# original type (str) is first converted to float, multiplied and then converted back
df['hemo'] = df['hemo'].astype('Float64')
df['hemo'] = df['hemo'].apply(lambda x: x*10)
df['hemo'] = df['hemo'].astype(str)
df

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc,class
0,48,80,1.020,1,0,121,36,NaN,NaN,154.0,44,7800,5.2,ckd
1,7,50,1.020,4,0,NaN,18,NaN,NaN,113.0,38,6000,NaN,ckd
2,62,80,1.010,2,3,423,53,NaN,NaN,96.0,31,7500,NaN,ckd
3,48,70,1.005,4,0,117,56,111,2.5,112.0,32,6700,3.9,ckd
4,51,80,1.010,2,0,106,26,NaN,NaN,116.0,35,7300,4.6,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,12,80,1.020,0,0,100,26,137,4.4,158.0,49,6600,5.4,notckd
398,17,60,1.025,0,0,114,50,135,4.9,142.0,51,7200,5.9,notckd
399,58,80,1.025,0,0,131,18,141,3.5,158.0,53,6800,6.1,notckd
400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# recodes class values 'ckd' and 'notckd' (chronic kidney disease, control) to 'a' and 'c'
df['class'] = df['class'].replace({'ckd':'a', 'notckd':'c'})
df

,age,bp,sg,al,su,bgr,bu,sod,pot,hemo,pcv,wbcc,rbcc,class
0,48,80,1.020,1,0,121,36,NaN,NaN,154.0,44,7800,5.2,a
1,7,50,1.020,4,0,NaN,18,NaN,NaN,113.0,38,6000,NaN,a
2,62,80,1.010,2,3,423,53,NaN,NaN,96.0,31,7500,NaN,a
3,48,70,1.005,4,0,117,56,111,2.5,112.0,32,6700,3.9,a
4,51,80,1.010,2,0,106,26,NaN,NaN,116.0,35,7300,4.6,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,12,80,1.020,0,0,100,26,137,4.4,158.0,49,6600,5.4,c
398,17,60,1.025,0,0,114,50,135,4.9,142.0,51,7200,5.9,c
399,58,80,1.025,0,0,131,18,141,3.5,158.0,53,6800,6.1,c
400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# remove rows with three or more missing values
df = df[df.isnull().sum(axis=1) < 3]
df

    age  bp     sg al su  bgr  bu  sod  pot   hemo pcv  wbcc rbcc class
0    48  80  1.020  1  0  121  36  NaN  NaN  154.0  44  7800  5.2     a
3    48  70  1.005  4  0  117  56  111  2.5  112.0  32  6700  3.9     a
4    51  80  1.010  2  0  106  26  NaN  NaN  116.0  35  7300  4.6     a
5    60  90  1.015  3  0   74  25  142  3.2  122.0  39  7800  4.4     a
6    68  70  1.010  0  0  100  54  104  4.0  124.0  36   NaN  NaN     a
..   ..  ..    ... .. ..  ...  ..  ...  ...    ...  ..   ...  ...   ...
395  55  80  1.020  0  0  140  49  150  4.9  157.0  47  6700  4.9     c
396  42  70  1.025  0  0   75  31  141  3.5  165.0  54  7800  6.2     c
397  12  80  1.020  0  0  100  26  137  4.4  158.0  49  6600  5.4     c
398  17  60  1.025  0  0  114  50  135  4.9  142.0  51  7200  5.9     c
399  58  80  1.025  0  0  131  18  141  3.5  158.0  53  6800  6.1     c

[266 rows x 14 columns]

In [7]:
# reindex dataframe to correctly show the number of rows left
df = df.reset_index(drop=True)
df

    age  bp     sg al su  bgr  bu  sod  pot   hemo pcv  wbcc rbcc class
0    48  80  1.020  1  0  121  36  NaN  NaN  154.0  44  7800  5.2     a
1    48  70  1.005  4  0  117  56  111  2.5  112.0  32  6700  3.9     a
2    51  80  1.010  2  0  106  26  NaN  NaN  116.0  35  7300  4.6     a
3    60  90  1.015  3  0   74  25  142  3.2  122.0  39  7800  4.4     a
4    68  70  1.010  0  0  100  54  104  4.0  124.0  36   NaN  NaN     a
..   ..  ..    ... .. ..  ...  ..  ...  ...    ...  ..   ...  ...   ...
261  55  80  1.020  0  0  140  49  150  4.9  157.0  47  6700  4.9     c
262  42  70  1.025  0  0   75  31  141  3.5  165.0  54  7800  6.2     c
263  12  80  1.020  0  0  100  26  137  4.4  158.0  49  6600  5.4     c
264  17  60  1.025  0  0  114  50  135  4.9  142.0  51  7200  5.9     c
265  58  80  1.025  0  0  131  18  141  3.5  158.0  53  6800  6.1     c

[266 rows x 14 columns]